---
name: Check styling
on:
  pull_request:
  push:
    branches:
      - trying
      - staging
jobs:
  build-deploy:
    name: check style
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn install
    - run: yarn style
